In [14]:
#starting data
import glob
import re
from pathlib import Path

trajectory_path = '/Users/kadendimarco/Desktop/Shrivinas_lab/genome_archetecture/chromosomes_openmm/polychrom_base/benchmarking/hp_traj_cones_bm/custom_sticky_force_conf_cp_bl'

block_files = glob.glob(str(Path(trajectory_path) / "blocks_*.h5"))

# Sort block files numerically based on block number
def extract_start_index(filename):
    match = re.search(r'blocks_(\d+)-\d+\.h5', filename)
    return int(match.group(1)) if match else -1

# Sort by the extracted start index
block_files_sorted = sorted(block_files, key=extract_start_index)

print(block_files_sorted)

#throw out first few blocks
block_files_sorted = block_files_sorted[5:]




['/Users/kadendimarco/Desktop/Shrivinas_lab/genome_archetecture/chromosomes_openmm/polychrom_base/benchmarking/hp_traj_cones_bm/custom_sticky_force_conf_cp_bl/blocks_0-499.h5', '/Users/kadendimarco/Desktop/Shrivinas_lab/genome_archetecture/chromosomes_openmm/polychrom_base/benchmarking/hp_traj_cones_bm/custom_sticky_force_conf_cp_bl/blocks_500-999.h5', '/Users/kadendimarco/Desktop/Shrivinas_lab/genome_archetecture/chromosomes_openmm/polychrom_base/benchmarking/hp_traj_cones_bm/custom_sticky_force_conf_cp_bl/blocks_1000-1002.h5', '/Users/kadendimarco/Desktop/Shrivinas_lab/genome_archetecture/chromosomes_openmm/polychrom_base/benchmarking/hp_traj_cones_bm/custom_sticky_force_conf_cp_bl/blocks_1003-1003.h5', '/Users/kadendimarco/Desktop/Shrivinas_lab/genome_archetecture/chromosomes_openmm/polychrom_base/benchmarking/hp_traj_cones_bm/custom_sticky_force_conf_cp_bl/blocks_1004-1004.h5', '/Users/kadendimarco/Desktop/Shrivinas_lab/genome_archetecture/chromosomes_openmm/polychrom_base/benchmar

There are 8 chains, 4 copies of each chromosome. I will process as usual and then aggregate (should be 12,000 X12,000 at end)

Go from 48,000X3 to 48,000X48,000

something like this
for i in range pos[]

misc info
print(np.min(pos))  ->  -149.1
print(np.max(pos))  ->  100.55



In [19]:
#just for first file
#This used more than 12GB memory and I had to stop it...

import h5py
import numpy as np

# Get the first block file from your sorted list
first_block_file = block_files_sorted[1]
print(f"Examining file: {first_block_file}")

spatial_distance_bins = {}

with h5py.File(first_block_file, 'r') as f:
    # Print the structure
    print("\nFile structure:")
    print("Groups:", list(f.keys()))
    
    # Look at the first block (group '0')
    first_group = f['0']
    print("\nFirst block contents:")
    print("Datasets in block:", list(first_group.keys()))
    
    # pos is NX3 array
    pos = first_group['pos'][:]
    print(pos.shape)

    N = pos.shape[0]
    # for i in range(N):
    #     for j in range(i+1, N):
    #         monomer_index_separation = j-i
    #         spatial_distance = np.linalg.norm(pos[i] - pos[j])
    #         if monomer_index_separation not in spatial_distance_bins:
    #             spatial_distance_bins[monomer_index_separation] = []
    #         else:
    #             spatial_distance_bins[monomer_index_separation].append(spatial_distance)
    

Examining file: /Users/kadendimarco/Desktop/Shrivinas_lab/genome_archetecture/chromosomes_openmm/polychrom_base/benchmarking/hp_traj_cones_bm/custom_sticky_force_conf_cp_bl/blocks_1006-1006.h5

File structure:
Groups: ['1006']


KeyError: "Unable to synchronously open object (object '0' doesn't exist)"

In [10]:
print(np.max(pos))

100.55


In [11]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

# Assume pos is a (48000, 3) numpy array
# Step 1: Compute the pairwise distance matrix
dist_matrix = squareform(pdist(pos))  # shape (48000, 48000)

# Step 2: Initialize best triplet and distance
best_triplet = None
min_total_dist = np.inf

# Step 3: Loop over each point and check closest two others
for i in range(len(pos)):
    # Get distances from point i to all others
    dists = dist_matrix[i]
    dists[i] = np.inf  # ignore self-distance

    # Find two nearest neighbors to i
    nearest = np.argpartition(dists, 2)[:2]
    
    # Compute total distance between the 3 points
    i1, i2 = nearest
    total_dist = dists[i1] + dists[i2] + dist_matrix[i1, i2]

    if total_dist < min_total_dist:
        min_total_dist = total_dist
        best_triplet = (i, i1, i2)

# Step 4: Print result
print("Closest triplet indices:", best_triplet)
print("Coordinates:\n", pos[list(best_triplet)])


Closest triplet indices: (25098, 25280, 25279)
Coordinates:
 [[ 58.9   45.52 -43.51]
 [ 58.83  45.67 -43.44]
 [ 59.41  44.88 -43.63]]


In [ ]:
print(pos[25098])

[ 58.9   45.52 -43.51]


In [21]:
import h5py
import numpy as np

# Get the first block file
first_block_file = block_files_sorted[1]
print(f"Examining file: {first_block_file}")

with h5py.File(first_block_file, 'r') as f:
    # Print the structure
    print("\nFile structure:")
    print("Groups:", list(f.keys()))
    
    # Get the first group name
    first_group_name = list(f.keys())[0]
    print(f"\nFirst group name: {first_group_name}")
    
    # Look at the first block
    first_group = f[first_group_name]
    print("\nFirst block contents:")
    print("Datasets in block:", list(first_group.keys()))

Examining file: /Users/kadendimarco/Desktop/Shrivinas_lab/genome_archetecture/chromosomes_openmm/polychrom_base/benchmarking/hp_traj_cones_bm/custom_sticky_force_conf_cp_bl/blocks_1006-1006.h5

File structure:
Groups: ['1006']

First group name: 1006

First block contents:
Datasets in block: ['pos']
